---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Custome pallettes

Just some custom palettes

## Installation

You can install this set of custom palettes from GitHub with:

```{r eval = FALSE}
# install.packages("devtools")
devtools::install_github("fschleef/custom_pallettes")
```


## Example

You can create a palette in just one command (+ get an image of the palette).

```{r results = 'show'}
pal <- custom_palette("LeaLebanon")
```

If you want a specific number of colors, you can also do that.

```{r}
pal <- custom_palette("LeaLebanon", 5)
```

## Palettes

```{r out.width="300px", echo = FALSE, warning = FALSE, message = FALSE}
print.palette <- function(x, ...) {
  n <- length(x)
  old <- par(mar = c(0.5, 0.5, 0.5, 0.5))
  on.exit(par(old))

  image(1:n, 1, as.matrix(1:n), col = x,
        ylab = "", xaxt = "n", yaxt = "n", bty = "n")

  rect(0, 0.9, n + 1, 1.1, col = rgb(1, 1, 1, 0.8), border = NA)
  text((n + 1) / 2, 1, labels = attr(x, "name"), cex = 2, family = "Lato", col = "#32373D")
}

print.palette(custom_palette(pal))
```

